name: CI                          # name shown in the Actions tab

on:
  push:                           # trigger on every push
    branches:
      - '**'                      # to any branch

jobs:
  build:
    runs-on: ubuntu-latest        # fresh Ubuntu machine every run

    steps:
      - name: Check out code
        uses: actions/checkout@v4         # copies your repo onto the machine

      - name: Set up Python
        uses: actions/setup-python@v6     # installs Python 3.12
        with:
          python-version: '3.12'

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2    # official AWS action for SAM

      - name: Build
        run: sam build                    # compiles your Lambda code